railsama/railsama/config/routes.rb
Railsama::Application.routes.draw do
  
  root :to => 'amas#new'
  resources :amas
  
  match ':about' => 'staticpage#about', :as => 'about'
  
  
  

  

end

railsama/railsama/app/models/ama.rb
require 'rubygems'
require 'json'
require 'net/http'
require 'comment'
require 'snoo'
require 'uri'

class Ama < ActiveRecord::Base
  attr_accessible :author, :url, :title, :date, :threadhash
  before_validation :add_url_protocol
  regexurl = Regexp.new("(http:\/\/)?www\.reddit\.com\/r\/IAmA\/comments\/[a-z0-9\/_]*", "i")
  validates :url, :format => { :with => regexurl,
    :message => "That doesn't look like the URL of an AMA."}
  has_many :comments, :dependent => :destroy
  
  def download
    if date.nil? or Time.now - date > 60 
      result = JSON.parse(Net::HTTP.get_response(URI.parse(url + ".json")).body)
      h = {:author => result[0]['data']['children'][0]['data']['author'], :title => result[0]['data']['children'][0]['data']['title'],
         :date => Time.now, :threadhash => result[0]['data']['children'][0]['data']['name']}
      self.update_attributes(h)
      toplevel(result)
    end
  end
  
  def add_url_protocol
    unless self.url[/^http:\/\//]
      self.url = 'http://' + self.url
    end
  end

   def toplevel(result)    
     result[1]['data']['children'].each do |x|
       traverse_thread(x['data'], nil)
   	end
  end
  
  def traverse_thread(thread, parent)
    if thread['author'] == author
      create_comment(parent) if parent
      create_comment(thread)
    end
    unless thread['replies'].nil? or thread['replies']['data'].nil?
      thread['replies']['data']['children'].each do |reply|
        traverse_thread(reply['data'], thread)
      end
    end
  end

  def create_comment(thread)
    h = {:body => thread['body'], :unique_id => thread['name'], :parent_id => thread['parent_id'], :author => thread['author']}
    comment = Comment.find_or_create_by_unique_id(thread['name'])
    comment.update_attributes(h)
    comment.ama = self
    comment.save
  end
  
  def self.top_link(threadhash)
     reddit = Snoo::Client.new
     toplink = reddit.get_listing({:subreddit =>"IAMA", :page=>"top", :t =>"day", :limit=>1, :after=>threadhash})
     if !toplink['data']['children'][0]['data']['title'].downcase.include? "request"
       parse_me = toplink['data']['children'][0]['data']['url'] + ".json"
       result = JSON.parse(Net::HTTP.get_response(URI.parse(parse_me)).body)
       @topama = Ama.find_or_create_by_url(result[0]['data']['children'][0]['data']['url'])
       h = {:author => result[0]['data']['children'][0]['data']['author'], :title => result[0]['data']['children'][0]['data']['title'],
         :date => Time.now, :threadhash => result[0]['data']['children'][0]['data']['name'],
         :url => result[0]['data']['children'][0]['data']['url']}
      @topama.update_attributes(h)
      @topama.toplevel(result)
      return @topama.id
    else 
      top_link(toplink['data']['children'][0]['data']['name'])
    end
   end
   
   def display_thread(uid, list)
     comments.each do |comm|
       if comm.parent_id == uid
         list.push(comm)
         display_thread(comm.unique_id, list)
       end
    end
    return list
  end
end

railsama/railsama/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ama	
	attr_accessible :body
	attr_accessible :unique_id
	attr_accessible :parent_id
	attr_accessible :author
end

railsama/railsama/app/controllers/amas_controller.rb
require 'snoo'
require 'json'
require 'net/http'
class AmasController < ApplicationController
  # GET /amas
  # GET /amas.json
  #before_filter :ban_pages, except: [:show, :new]
  
  # GET /amas/1
  # GET /amas/1.json
  def show
    @ama = Ama.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ama }
    end
  end

  # GET /amas/new
  # GET /amas/new.json
  def new
    @ama = Ama.new
 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ama }
    end
  end

  # GET /amas/1/edit
  def edit
    @ama = Ama.find(params[:id])
  end

  # POST /amas
  # POST /amas.json
  def create
    @ama = Ama.find_or_create_by_url(params[:ama][:url])

    respond_to do |format|
      if @ama.save and @ama.download
        format.html { redirect_to @ama, notice: 'Ama was successfully created.' }
        format.json { render json: @ama, status: :created, location: @ama }
      else
        format.html { render action: "new" }
        format.json { render json: @ama.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /amas/1
  # PUT /amas/1.json
  def update
    @ama = Ama.find(params[:id])

    respond_to do |format|
      if @ama.update_attributes(params[:ama])
        format.html { redirect_to @ama, notice: 'Ama was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ama.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amas/1
  # DELETE /amas/1.json
  def destroy
    @ama = Ama.find(params[:id])
    @ama.destroy

    respond_to do |format|
      format.html { redirect_to amas_url }
      format.json { head :no_content }
    end
  end
end

railsama/railsama/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def ban_pages
    redirect_to "/amas/new"
  end
  
end

railsama/railsama/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

railsama/railsama/app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController
  
  def about
  end
end

railsama/railsama/app/helpers/amas_helper.rb
require 'bluecloth'
module AmasHelper
  def m(string)
    BlueCloth.new(string).to_html()
  end
end

railsama/railsama/app/helpers/application_helper.rb
module ApplicationHelper
end

railsama/railsama/app/helpers/comments_helper.rb
module CommentsHelper
end

railsama/railsama/app/helpers/staticpage_helper.rb
module StaticpageHelper
end

railsama/railsama/app/views/amas/_form.html.erb
<%= form_for(@ama) do |f| %>
  <% if @ama.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ama.errors.count, "error") %> prohibited this ama from being saved:</h2>

      <ul>
      <% @ama.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id ="frm">
	<div class="group">
  		<div class="field">
    		<%= f.text_field(:url, :class => "input-xlarge") %>
  		</div>
	</div>
	<div class="group">
  		<div class="actions">
    		<%= f.submit %>
  		</div>
	</div>
</div>
<% end %>

railsama/railsama/app/views/amas/edit.html.erb
<h1>Editing ama</h1>

<%= render 'form' %>

<%= link_to 'Show', @ama %> |
<%= link_to 'Back', amas_path %>

railsama/railsama/app/views/amas/index.html.erb
<h1>Listing amas</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @amas.each do |ama| %>
  <tr>
    <td><%= ama.url %></td>
    <td><%= ama.author %></td>
    <td><%= link_to 'Show', ama %></td>
    <td><%= link_to 'Edit', edit_ama_path(ama) %></td>
    <td><%= link_to 'Destroy', ama, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ama', new_ama_path %>

railsama/railsama/app/views/amas/new.html.erb
<body>
<div id="col1"></div>
<div id="col2">
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	
	<h2>Enter the URL of an AMA:</h2>

	<%= render 'form' %>
	
	
	<% top_title = Ama.find(Ama.top_link(nil)).title%> 

	<br>
	<br>
	<br>
	<br>
	<br>
	<br>


	<h3> Or read today's most popular AMA: </h3>
	<h3 class="small"><%= link_to top_title, ama_path(Ama.top_link(nil)) %> </h3>
	
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<p class="center"><%= link_to "About this site", about_path('about')%> |
	<a href="https://github.com/elanakoren/amaproject/tree/master/railsama/railsama">Source code</a></p>
</div>
</body>

railsama/railsama/app/views/amas/show.html.erb
<h1 class = "h1_neat" style = "margin:10px">
	<% @profile_link = "http://www.reddit.com/user/#{@ama.author}"%>
	<a href="<%=@ama.url%>">"<%= @ama.title %>"</a> by 
	<a href="<%=@profile_link%>"><%=@ama.author %></a>
</h1>

<%@ama.comments.each do |comm|%>
	<%if comm.parent_id == @ama.threadhash %> <br><br>
		<%@thread = @ama.display_thread(comm.unique_id, [comm])%>
		<%@thread.each do |threadcomm|%>
			<div class= "box_round" style="margin:10px;width:76.5%;border:1px solid gray;padding:8px;background:#BFEFFF;">
				<p><%=threadcomm.author%> writes:</p>
				<p><%=raw m threadcomm.body%></p>
			</div>
		<%end%>
	<%end%>
<% end %>

railsama/railsama/app/views/layouts/ama.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railsama" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Railsama</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

railsama/railsama/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsama</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

railsama/railsama/app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railsama" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Railsama</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>